version: '3.9'

services:
  db:
    image: postgres:16
    volumes:
      - postgres-data:/var/lib/postgresql
    env_file:
      - .env
  web:
    build: .
    command: tail -f /dev/null
    # command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  postgres-data:
    driver: local
    